name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - uses: actions/cache@v2
        with:
          path: |
            .cache
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-cache-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Run lint, test and build
        run: |
          make build
      - name: Create package
        run: |
          GOARCH=amd64 make package
          GOARCH=arm64 make package
      - uses: actions/upload-artifact@v2
        with:
          name: alfredworkflow
          path: dist/*.alfredworkflow
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: alfredworkflow
          path: dist/
      - name: Following artifacts will be published
        run: |
          ls -l dist/*.alfredworkflow
      - name: Publish
        if: ${{ github.event_name != 'pull_request' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=v$(cat VERSION)
          if git show-ref --tags | grep -q "refs/tags/${TAG}"
          then
            echo "${TAG} exists. Skipped"
          else
            git tag ${TAG}
            git push --tags
            gh release create ${TAG} -n "${TAG}" dist/*.alfredworkflow
          fi